name: "dev-app-next"

services:
  dev-app-next:
    image: ghcr.io/dince-afk/dev-app-next:latest
    user: root # Required for write access to mounted SQLite database
    env_file:
      - .env
    volumes:
      - ./payload.db:/app/payload.db
      - ./images:/app/images
    restart: unless-stopped
    networks:
      - caddy_network
    ports:
      - 3000
networks:
  caddy_network:
    name: caddy_network
    external: true
